# Generated by Django 4.1.6 on 2023-02-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceName',
            fields=[
                ('face_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('face_name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField()),
                ('face_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.facename')),
            ],
        ),
    ]
