# Generated by Django 4.1.6 on 2023-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceName',
            fields=[
                ('face_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('face_name', models.TextField(max_length=255)),
            ],
        ),
    ]
